<?php

namespace App\Enums;

enum PermissionEnum: string{
    case MELIHAT_DASHBOARD = "MELIHAT DASHBOARD";

    case MEMBUAT_PENGUNA = "MEMBUAT PENGUNA";
    case MENGHAPUS_PENGUNA = "MENGHAPUS PENGUNA";
    case MENGEDIT_PENGUNA = "MENGEDIT PENGUNA";
    case MELIHAT_PENGUNA = "MELIHAT PENGUNA";
    case MELIHAT_DETAIL_PENGUNA = "MELIHAT DETAIL PENGUNA";
    case MENGUBAH_PASSWORD_PENGUNA = "MENGUBAH PASSWORD PENGUNA";


    case MEMBUAT_ROLE = "MEMBUAT ROLE";
    case MENGHAPUS_ROLE = "MENGHAPUS ROLE";
    case MENGEDIT_ROLE = "MENGEDIT ROLE";
    case MELIHAT_ROLE = "MELIHAT ROLE";
    case MELIHAT_DETAIL_ROLE = "MELIHAT DETAIL ROLE";

    case MELIHAT_SALES_INVOICE = "MELIHAT SALES INVOICE";
    case MEMBUAT_SALES_INVOICE = "MEMBUAT SALES INVOICE";
    case MENGEDIT_NOMOR_SALES_INVOICE = "MENGEDIT NOMOR SALES INVOICE";
    case MENGEDIT_SALES_INVOICE = "MENGEDIT SALES INVOICE";
    case MENGHAPUS_SALES_INVOICE = "MENGHAPUS SALES INVOICE";
    case MELIHAT_DETAIL_SALES_INVOICE = "MELIHAT DETAIL SALES INVOICE";
    case MENYETUJUI_SALES_INVOICE = "MENYETUJUI SALES INVOICE";
    case VOID_SALES_INVOICE ="VOID SALES INVOICE";
    case MELIHAT_CATATAN_PERUBAHAN_SALES_INVOICE = "MELIHAT CATATAN PERUBAHAN SALES INVOICE";
    case MELIHAT_CATATAN_PERUBAHAN_DETAIL_SALES_INVOICE = "MELIHAT CATATAN PERUBAHAN DETAIL SALES INVOICE";


    case MELIHAT_PIUTANG = "MELIHAT PIUTANG";
    case MEMBUAT_PIUTANG = "MEMBUAT PIUTANG";
    case MENYETUJUI_PIUTANG = "MENYETUJUI PIUTANG";
    case MENOLAK_PIUTANG = "MENOLAK PIUTANG";
    case MENGEDIT_PIUTANG = "MENGEDIT PIUTANG";
    case MELIHAT_DETAIL_PIUTANG = "MELIHAT DETAIL PIUTANG";

    case MELIHAT_PEMBAYARAN_PIUTANG = "MELIHAT PEMBAYARAN PIUTANG";
    case MEMBUAT_PEMBAYARAN_PIUTANG = "MEMBUAT PEMBAYARAN PIUTANG";
    case MENGEDIT_PEMBAYARAN_PIUTANG = "MENGEDIT PEMBAYARAN PIUTANG";
    case MENGHAPUS_PEMBAYARAN_PIUTANG = "MENGHAPUS PEMBAYARAN PIUTANG";

    case MELIHAT_LAPORAN_SHIFT = "MELIHAT LAPORAN SHIFT";
    case MELIHAT_DETAIL_LAPORAN_SHIFT = "MELIHAT DETAIL LAPORAN SHIFT";
    case MEMBUKA_SHIFT = "MEMBUKA SHIFT";
    case MENUTUP_SHIFT = "MENUTUP SHIFT";

    case MENAMBAH_BIAYA_OPERATIONAL = "MENAMBAH BIAYA OPERATIONAL";
    case MELIHAT_BIAYA_OPERATIONAL = "MELIHAT BIAYA OPERATIONAL";
    case MENGEDIT_BIAYA_OPERATIONAL = "MENGEDIT BIAYA OPERATIONAL";
    case MENGHAPUS_BIAYA_OPERATIONAL = "MENGHAPUS BIAYA OPERATIONAL";
    case MENYETUJUI_BIAYA_OPERATIONAL = "MENYETUJUI BIAYA OPERATIONAL";
    case MENOLAK_BIAYA_OPERATIONAL = "MENOLAK BIAYA OPERATIONAL";

    case MELIHAT_METODE_PEMBAYARAN = "MELIHAT METODE PEMBAYARAN";
    case MEMBUAT_METODE_PEMBAYARAN ="MEMBUAT METODE PEMBAYARAN";
    case MENGEDIT_METODE_PEMBAYARAN = "MENGEDIT METODE PEMBAYARAN";
    case MENGHAPUS_METODE_PEMBAYARAN = "MENGHAPUS METODE PEMBAYARAN";

    case MELIHAT_DETAIL_METODE_PEMBAYARAN = "MELIHAT DETAIL METODE PEMBAYARAN";

    case MELIHAT_TIPE_PEMBAYARAN  = "MELIHAT TIPE PEMBAYARAN";
    case MEMBUAT_TIPE_PEMBAYARAN = "MEMBUAT TIPE PEMBAYARAN";
    case MENGHAPUS_TIPE_PEMBAYARAN = "MENGHAPUS TIPE PEMBAYARAN";
    case MENGEDIT_TIPE_PEMBAYARAN = "MENGEDIT TIPE PEMBAYARAN";
    case MELIHAT_DETAIL_TIPE_PEMBAYARAN = "MELIHAT DETAIL TIPE PEMBAYARAN";

    case MELIHAT_LEASING = "MELIHAT LEASING";
    case MENAMBAH_LEASING = "MENAMBAH LEASING";
    case MENGEDIT_LEASING = "MENGEDIT LEASING";
    case MENGHAPUS_LEASING = "MENGHAPUS LEASING";
    case MELIHAT_DETAIL_LEASING = "MELIHAT DETAIL LEASING";

    case MELIHAT_REKAPAN_TRANSAKSI_HARIAN = "MELIHAT REKAPAN TRANSAKSI HARIAN";

    case MENAMBAH_HUTANG_DAGANG = "MENAMBAH HUTANG DAGANG";
    case MELIHAT_HUTANG_DAGANG = "MELIHAT HUTANG DAGANG";
    case MENGEDIT_HUTANG_DAGANG = "MENGEDIT HUTANG DAGANG";
    case MENGHAPUS_HUTANG_DAGANG = "MENGHAPUS HUTANG DAGANG";
    case MELIHAT_DETAIL_HUTANG_DAGANG = "MELIHAT DETAIL HUTANG DAGANG";
    case MENYETUJUI_HUTANG_DAGANG = "MENYETUJUI HUTANG DAGANG";
    case MENOLAK_HUTANG_DAGANG = "MENOLAK HUTANG DAGANG";

    case MENGEDIT_SETTING = "MENGEDIT SETTING";
    case MELIHAT_SETTING ="MELIHAT SETTING";

}