<?php

namespace App\Enums;

enum PermissionEnum: string{
    case MELIHAT_DASHBOARD = "MELIHAT DASHBOARD";

    case MEMBUAT_PENGUNA = "MEMBUAT PENGUNA";
    case MENGHAPUS_PENGUNA = "MENGHAPUS PENGUNA";
    case MENGEDIT_PENGUNA = "MENGEDIT PENGUNA";
    case MELIHAT_PENGUNA = "MELIHAT PENGUNA";
    case MELIHAT_DETAIL_PENGUNA = "MELIHAT DETAIL PENGUNA";
    case MENGUBAH_PASSWORD_PENGUNA = "MENGUBAH PASSWORD PENGUNA";

    case MELIHAT_SUPPLIER = "MELIHAT SUPPLIER";
    case MEMBUAT_SUPPLIER = "MEMBUAT  SUPPLIER";
    case MENGEDIT_SUPPLIER = "MENGEDIT SUPPLIER";
    case MENGHAPUS_SUPPLIER = "MENGHAPUS SUPPLIER";

      case MELIHAT_CUSTOMER = "MELIHAT CUSTOMER";
    case MEMBUAT_CUSTOMER = "MEMBUAT  CUSTOMER";
    case MENGEDIT_CUSTOMER = "MENGEDIT CUSTOMER";
    case MENGHAPUS_CUSTOMER = "MENGHAPUS CUSTOMER";

    case MELIHAT_PRODUCT = "MELIHAT PRODUCT";
    case MEMBUAT_PRODUCT = "MEMBUAT PRODUCT";
    case MENGEDIT_PRODUCT = "MENGEDIT PRODUCT";
    case MENGHAPUS_PRODUCT = "MENGHAPUS PRODUCT";

    case MELIHAT_PRODUCT_SKU = "MELIHAT PRODUCT SKU";
    case MEMBUAT_PRODUCT_SKU = "MEMBUAT PRODUCT SKU";
    case MENGEDIT_PRODUCT_SKU = "MENGEDIT PRODUCT SKU";
    case MENGHAPUS_PRODUCT_SKU = "MENGHAPUS_PRODUCT_SKU";

    case MELIHAT_PRODUCT_CATEGORY = "MELIHAT PRODUCT CATEGORY";
    case MEMBUAT_PRODUCT_CATEGORY  = "MEMBUAT PRODUCT CATEGORY";
    case MENGEDIT_PRODUCT_CATEGORY  = "MENGEDIT PRODUCT CATEGORY";
    case MENGHAPUS_PRODUCT_CATEGORY  = "MENGHAPUS PRODUCT CATEGORY";

    case MEMBUAT_ROLE = "MEMBUAT ROLE";
    case MENGHAPUS_ROLE = "MENGHAPUS ROLE";
    case MENGEDIT_ROLE = "MENGEDIT ROLE";
    case MELIHAT_ROLE = "MELIHAT ROLE";
    case MELIHAT_DETAIL_ROLE = "MELIHAT DETAIL ROLE";

    case MELIHAT_INBOUND = "MELIHAT INBOUND";
    case MEMBUAT_INBOUND = "MEMBUAT INBOUND";
    case MENYETUJUI_INBOUND= "MENYETUJUI INBOUND";
    case MENOLAK_INBOUND = "MENOLAK INBOUND";

    case MELIHAT_OUTBOUND = "MELIHAT OUTBOUND";
    case MEMBUAT_OUTBOUND = "MEMBUAT OUTBOUND";
    case MENYETUJUI_OUTBOUND = "MENYETUJUI OUTBOUND";
    case MENOLAK_OUTBOUND = "MENOLAK OUTBOUND";

    case MELIHAT_MUTATION_IN = "MELIHAT MUTATION IN";
    case MEMBUAT_MUTATION_IN = "MEMBUAT MUTATION IN";
    case MENGEDIT_MUTATION_IN = "MENGEDIT MUTATION IN";
    case MENOLAK_MUTATION_IN = "MENOLAK MUTATION IN";
    case MENYETUJUI_MUTATION_IN = "MENYETUJUI MUTATION IN";

    case MELIHAT_WAREHOUSE ="MELIHAT WAREHOUSE";
    case MEMBUAT_WAREHOUSE = "MEMBUAT WAREHOUSE";
    case MENGEDIT_WAREHOUSE = "MENGEDIT WAREHOUSE";
    case MENGHAPUS_WAREHOUSE ="MENGHAPUS WAREHOUSE";

    case MELIHAT_MUTATION_OUT = "MELIHAT MUTATION OUT";
case MEMBUAT_MUTATION_OUT = "MEMBUAT MUTATION OUT";
    case MENGEDIT_MUTATION_OUT = "MENGEDIT MUTATION OUT";
    case MENOLAK_MUTATION_OUT = "MENOLAK MUTATION OUT";
    case MENYETUJUI_MUTATION_OUT = "MENYETUJUI MUTATION OUT";

    case MELIHAT_INVENTORY ="MELIHAT INVENTORY";
    case MELIHAT_PERGERAKAN_STOK = "MELIHAT PERGERAKAN STOK";

    case MELIHAT_PENYESUAIAN_STOK = "MELIHAT PENYESUAIAN STOK";
    case MEMBUAT_PENYESUAIAN_STOK = "MEMBUAT PENYESUAIAN STOK";
    case MENGEDIT_PENYESUAIAN_STOK = "MENGEDIT PENYESUAIAN STOK";
    case MENOLAK_PENYESUAIAN_STOK = "MENOLAK PENYESUAIAN STOK";
    case MENYETUJUI_PENYESUAIAN_STOK = "MENYETUJUI PENYESUAIAN STOK";

    case MENGEDIT_SETTING = "MENGEDIT SETTING";
    case MELIHAT_SETTING ="MELIHAT SETTING";

}