<?php

namespace App\Enums;

enum SalesInvoiceStatusEnum: string {
    case DIBUAT = "DIBUAT";
    case PERLU_DILENGKAPI = "PERLU DILENGKAPI";
    case BELUM_LUNAS = "BELUM LUNAS";
    case MEMERLUKAN_PERSETUJUAN_PIUTANG = "MEMERLUKAN PERSETUJUAN PIUTANG";
    case DISETUJUI_MENJADI_PIUTANG = "DISETUJUI MENJADI PIUTANG";
    case DIBAYARKAN_PARSIAL = "DIBAYARKAN PARSIAL";     
    case DIBAYARKAN_KESELURUHAN = "DIBAYARKAN KESELURUHAN";

    case LUNAS = "LUNAS";
    case VOID = "VOID";
}